// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190512211231_updateProductVersion")]
    partial class updateProductVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId");

                    b.Property<int?>("PostCityId");

                    b.Property<string>("Street");

                    b.Property<string>("StreetBus");

                    b.Property<int?>("StreetNumber");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("PostCityId");

                    b.ToTable("Adress");
                });

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdressId");

                    b.Property<string>("BrandName")
                        .IsRequired();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<int?>("QualityId");

                    b.Property<string>("WebSite");

                    b.HasKey("Id");

                    b.HasIndex("AdressId")
                        .IsUnique()
                        .HasFilter("[AdressId] IS NOT NULL");

                    b.HasIndex("QualityId");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocationName")
                        .IsRequired();

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Entities.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MetricName");

                    b.HasKey("Id");

                    b.ToTable("Metric");
                });

            modelBuilder.Entity("Entities.Models.PostCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("PostCode")
                        .IsRequired();

                    b.Property<string>("Province");

                    b.Property<bool?>("SubMunicipality");

                    b.HasKey("Id");

                    b.ToTable("PostCity");
                });

            modelBuilder.Entity("Entities.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price");

                    b.Property<decimal>("PricePerUnit");

                    b.HasKey("Id");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId");

                    b.Property<int?>("CategoryId");

                    b.Property<int?>("DefaultMetricId");

                    b.Property<string>("Description");

                    b.Property<decimal>("LatestPrice");

                    b.Property<decimal>("LatestPricePerUnit");

                    b.Property<string>("LinkPdfManual");

                    b.Property<int?>("LocationId");

                    b.Property<decimal>("LowestPrice");

                    b.Property<decimal>("LowestPricePerUnit");

                    b.Property<int?>("MetricId");

                    b.Property<int>("NumberInStock");

                    b.Property<string>("Picture");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired();

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<int?>("QualityId");

                    b.Property<int?>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MetricId");

                    b.HasIndex("QualityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Entities.Models.ProductVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DayOfPurchase");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("LinkScanTicket");

                    b.Property<int?>("MetricId");

                    b.Property<decimal>("Price");

                    b.Property<decimal>("PricePerUnit");

                    b.Property<int?>("ProductId");

                    b.Property<int>("QuantityInStock");

                    b.Property<int>("QuantityPurchased");

                    b.Property<int?>("SupplierId");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductVersion");
                });

            modelBuilder.Entity("Entities.Models.Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QualityName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Quality");
                });

            modelBuilder.Entity("Entities.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "ok"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Niet Ok"
                        });
                });

            modelBuilder.Entity("Entities.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdressId");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<string>("SupplierName")
                        .IsRequired();

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("AdressId")
                        .IsUnique()
                        .HasFilter("[AdressId] IS NOT NULL");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Entities.Models.Adress", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany("Adresses")
                        .HasForeignKey("CountryId");

                    b.HasOne("Entities.Models.PostCity", "PostCity")
                        .WithMany("Adresses")
                        .HasForeignKey("PostCityId");
                });

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.HasOne("Entities.Models.Adress", "Adress")
                        .WithOne("Brand")
                        .HasForeignKey("Entities.Models.Brand", "AdressId");

                    b.HasOne("Entities.Models.Quality")
                        .WithMany("Brands")
                        .HasForeignKey("QualityId");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.HasOne("Entities.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.HasOne("Entities.Models.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Entities.Models.Location", "Location")
                        .WithMany("Products")
                        .HasForeignKey("LocationId");

                    b.HasOne("Entities.Models.Metric", "Metric")
                        .WithMany("Products")
                        .HasForeignKey("MetricId");

                    b.HasOne("Entities.Models.Quality", "Quality")
                        .WithMany("Products")
                        .HasForeignKey("QualityId");

                    b.HasOne("Entities.Models.Status", "Status")
                        .WithMany("Products")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("Entities.Models.ProductVersion", b =>
                {
                    b.HasOne("Entities.Models.Metric", "Metric")
                        .WithMany("ProductVersions")
                        .HasForeignKey("MetricId");

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Entities.Models.Supplier", "Supplier")
                        .WithMany("ProductVersions")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("Entities.Models.Supplier", b =>
                {
                    b.HasOne("Entities.Models.Adress", "Adress")
                        .WithOne("Supplier")
                        .HasForeignKey("Entities.Models.Supplier", "AdressId");
                });
#pragma warning restore 612, 618
        }
    }
}
