// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190501215912_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Entities.Adress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryID");

                    b.Property<int?>("PostCityID");

                    b.Property<string>("Street");

                    b.Property<string>("StreetBus");

                    b.Property<int>("StreetNumber");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("PostCityID");

                    b.ToTable("Adress");
                });

            modelBuilder.Entity("Models.Entities.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdressId");

                    b.Property<string>("BrandName")
                        .IsRequired();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<int?>("QualityID");

                    b.Property<string>("WebSite");

                    b.HasKey("ID");

                    b.HasIndex("AdressId")
                        .IsUnique();

                    b.HasIndex("QualityID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Models.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Models.Entities.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Models.Entities.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocationName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Models.Entities.PostCity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("PostCode")
                        .IsRequired();

                    b.Property<string>("Province");

                    b.Property<bool>("SubMunicipality");

                    b.HasKey("ID");

                    b.ToTable("PostCity");
                });

            modelBuilder.Entity("Models.Entities.PriceHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price");

                    b.Property<decimal>("PricePerUnit");

                    b.HasKey("ID");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("Models.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandID");

                    b.Property<int?>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<decimal>("LatestPrice");

                    b.Property<decimal>("LatestPricePerUnit");

                    b.Property<string>("LinkPdfManual");

                    b.Property<int?>("LocationID");

                    b.Property<decimal>("LowestPrice");

                    b.Property<decimal>("LowestPricePerUnit");

                    b.Property<int>("NumberInStock");

                    b.Property<string>("Picture");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired();

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<int?>("QualityID");

                    b.Property<int?>("StatusID");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LocationID");

                    b.HasIndex("QualityID");

                    b.HasIndex("StatusID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Models.Entities.ProductVersion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DayOfPurchase");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<decimal>("LatestPrice");

                    b.Property<decimal>("LatestPricePerUnit");

                    b.Property<string>("LinkScanTicket");

                    b.Property<decimal>("LowestPrice");

                    b.Property<decimal>("LowestPricePerUnit");

                    b.Property<int?>("ProductID");

                    b.Property<int?>("SupplierID");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProductVersion");
                });

            modelBuilder.Entity("Models.Entities.Quality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QualityName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Quality");
                });

            modelBuilder.Entity("Models.Entities.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            StatusName = "ok"
                        },
                        new
                        {
                            ID = 2,
                            StatusName = "Niet Ok"
                        });
                });

            modelBuilder.Entity("Models.Entities.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdressId");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<string>("SupplierName")
                        .IsRequired();

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.HasIndex("AdressId")
                        .IsUnique();

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Models.Entities.Adress", b =>
                {
                    b.HasOne("Models.Entities.Country", "Country")
                        .WithMany("Adresses")
                        .HasForeignKey("CountryID");

                    b.HasOne("Models.Entities.PostCity", "PostCity")
                        .WithMany("Adresses")
                        .HasForeignKey("PostCityID");
                });

            modelBuilder.Entity("Models.Entities.Brand", b =>
                {
                    b.HasOne("Models.Entities.Adress", "Adress")
                        .WithOne("Brand")
                        .HasForeignKey("Models.Entities.Brand", "AdressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Entities.Quality")
                        .WithMany("Brands")
                        .HasForeignKey("QualityID");
                });

            modelBuilder.Entity("Models.Entities.Product", b =>
                {
                    b.HasOne("Models.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandID");

                    b.HasOne("Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Models.Entities.Location", "Location")
                        .WithMany("Products")
                        .HasForeignKey("LocationID");

                    b.HasOne("Models.Entities.Quality", "Quality")
                        .WithMany("Products")
                        .HasForeignKey("QualityID");

                    b.HasOne("Models.Entities.Status", "Status")
                        .WithMany("Products")
                        .HasForeignKey("StatusID");
                });

            modelBuilder.Entity("Models.Entities.ProductVersion", b =>
                {
                    b.HasOne("Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");

                    b.HasOne("Models.Entities.Supplier", "Supplier")
                        .WithMany("ProductVersions")
                        .HasForeignKey("SupplierID");
                });

            modelBuilder.Entity("Models.Entities.Supplier", b =>
                {
                    b.HasOne("Models.Entities.Adress", "Adress")
                        .WithOne("Supplier")
                        .HasForeignKey("Models.Entities.Supplier", "AdressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
